# app/schemas/schemas.py
# Kushagra Patel | Roll No. 2201302012 | Quantum University Roorkee
# LLM-Driven Purple Team Automation Framework — Pydantic v2 Data Models

from __future__ import annotations
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field, model_validator
import uuid


# ── Enums ─────────────────────────────────────────────────────────────────────

class TechniqueID(str, Enum):
    POWERSHELL       = "T1059.001"
    LSASS_DUMP       = "T1003.001"
    REGISTRY_PERSIST = "T1547.001"
    DLL_INJECTION    = "T1055.001"   # Process Injection via DLL
    VALID_ACCOUNTS   = "T1078"       # Login using stolen credentials
    SYSINFO_DISC     = "T1082"       # System Information Discovery
    WEB_PROTOCOL_C2  = "T1071.001"   # C2 over HTTP/HTTPS


class CoverageStatus(str, Enum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"


class LogSource(str, Enum):
    WINDOWS_EVENT = "windows_event"
    SYSMON        = "sysmon"
    POWERSHELL    = "powershell_operational"


# ── Red Engine Schemas ────────────────────────────────────────────────────────

class TelemetryLog(BaseModel):
    """A single fake Windows telemetry log entry generated by Red Engine."""

    log_id:        str           = Field(default_factory=lambda: str(uuid.uuid4()))
    technique_id:  TechniqueID
    technique_name: str
    timestamp:     datetime      = Field(default_factory=lambda: datetime.now(timezone.utc))
    log_source:    LogSource
    event_id:      int
    hostname:      str           = Field(default="WORKSTATION-01")
    username:      str           = Field(default="CORP\\SimUser")
    process_name:  str
    command_line:  Optional[str] = None
    parent_process: Optional[str] = None
    registry_key:  Optional[str] = None
    raw_log:       dict[str, Any] = Field(default_factory=dict)

    model_config = {"use_enum_values": True}


class RedEngineResult(BaseModel):
    """Output of the Red Engine after simulating a technique."""

    run_id:       str           = Field(default_factory=lambda: str(uuid.uuid4()))
    technique_id: TechniqueID
    generated_at: datetime      = Field(default_factory=lambda: datetime.now(timezone.utc))
    logs:         list[TelemetryLog]
    log_count:    int           = 0

    @model_validator(mode="after")
    def set_log_count(self) -> RedEngineResult:
        self.log_count = len(self.logs)
        return self

    model_config = {"use_enum_values": True}


# ── Blue Engine Schemas ───────────────────────────────────────────────────────

class SigmaRule(BaseModel):
    """A Sigma detection rule generated by Blue Engine via Claude API."""

    rule_id:      str      = Field(default_factory=lambda: str(uuid.uuid4()))
    title:        str
    description:  str
    technique_id: str
    status:       str      = "experimental"
    level:        str      = "high"
    logsource:    dict[str, str]
    detection:    dict[str, Any]
    condition:    str
    raw_yaml:     str      = ""
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class BlueEngineResult(BaseModel):
    """Output of the Blue Engine after calling Claude API."""

    run_id:       str      = Field(default_factory=lambda: str(uuid.uuid4()))
    technique_id: str
    sigma_rule:   SigmaRule
    prompt_tokens: int     = 0
    completion_tokens: int = 0
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ── Validator Engine Schemas ──────────────────────────────────────────────────

class ValidationDetail(BaseModel):
    """Per-log validation result — did the rule match this log?"""

    log_id:      str
    matched:     bool
    match_reason: Optional[str] = None


class ValidatorResult(BaseModel):
    """Output of the Validator Engine — coverage score and pass/fail."""

    run_id:          str            = Field(default_factory=lambda: str(uuid.uuid4()))
    technique_id:    str
    total_logs:      int
    matched_logs:    int
    coverage_score:  float          = 0.0
    status:          CoverageStatus
    details:         list[ValidationDetail]
    validated_at:    datetime       = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def compute_score(self) -> ValidatorResult:
        if self.total_logs > 0:
            self.coverage_score = round(self.matched_logs / self.total_logs, 4)
        return self

    model_config = {"use_enum_values": True}


# ── Orchestrator / Pipeline Schemas ──────────────────────────────────────────

class PipelineRequest(BaseModel):
    """API request body to trigger the full Purple Team pipeline."""

    technique_id: TechniqueID
    log_count:    int = Field(default=5, ge=1, le=50)
    save_artifacts: bool = True

    model_config = {"use_enum_values": True}


class PipelineResult(BaseModel):
    """Full end-to-end result of one Purple Team pipeline run."""

    pipeline_id:      str            = Field(default_factory=lambda: str(uuid.uuid4()))
    technique_id:     str
    red_result:       RedEngineResult
    blue_result:      BlueEngineResult
    validator_result: ValidatorResult
    overall_status:   CoverageStatus
    completed_at:     datetime       = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"use_enum_values": True}